name: Generate release-artifacts

# on events
on:
  release:
    types: 
        - created

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: 'cmd/blockchain-analyzer'
            name: 'blockchain-analyzer'
            compress: 'true'
            dest: 'dist'
      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/blockchain-analyzer-windows-amd64.tar.gz
          asset_name: blockchain-analyzer-windows-amd64.tar.gz
          asset_content_type: application/gzip
      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/blockchain-analyzer-linux-amd64.tar.gz
          asset_name: blockchain-analyzer-linux-amd64.tar.gz
          asset_content_type: application/gzip
      - name: Upload macOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/blockchain-analyzer-darwin-amd64.tar.gz
          asset_name: blockchain-analyzer-darwin-amd64.tar.gz
          asset_content_type: application/gzip
